source 'http://rubygems.org'

gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'pry'
gem 'rspec'
gem 'site_prism'
gem 'sentry-ruby'
gem 'nokogiri'
gem 'simplecov'
gem 'rest-client'
gem 'rubyXL'
gem 'parallel'